mkdir node_modules
mklink /J pip-webui-lib\node_modules node_modules
mklink /J pip-webui-test\node_modules node_modules
mklink /J pip-webui-css\node_modules node_modules
mklink /J pip-webui-core\node_modules node_modules
mklink /J pip-webui-rest\node_modules node_modules
mklink /J pip-webui-controls\node_modules node_modules
mklink /J pip-webui-layouts\node_modules node_modules
mklink /J pip-webui-nav\node_modules node_modules
mklink /J pip-webui-pictures\node_modules node_modules
mklink /J pip-webui-documents\node_modules node_modules
mklink /J pip-webui-locations\node_modules node_modules
mklink /J pip-webui-composite\node_modules node_modules
mklink /J pip-webui-errors\node_modules node_modules
mklink /J pip-webui-entry\node_modules node_modules
mklink /J pip-webui-help\node_modules node_modules
mklink /J pip-webui-guidance\node_modules node_modules
mklink /J pip-webui-settings\node_modules node_modules
mklink /J pip-webui-support\node_modules node_modules
mklink /J pip-webui\node_modules node_modules
